In [3]:
import keras
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD, Adam
from keras.utils import to_categorical

from sklearn.model_selection import train_test_split


In [4]:
data = np.load('food.npz')
x, y = data['x'], data['y']
x, y

(array([[-1.17273899, -1.74921225],
        [-1.32528414, -0.9805946 ],
        [ 0.84108223, -0.81966812],
        ...,
        [-0.22758009, -1.17369814],
        [-0.8487975 , -0.17594146],
        [ 1.09114043,  0.90788055]]),
 array([2, 2, 0, ..., 2, 2, 1], dtype=int64))

In [5]:
X_train, X_valid, y_train, y_valid = train_test_split(x, y, test_size=0.2)

In [6]:
y_train_onehot = to_categorical(y_train, num_classes=3)
y_valid_onehot = to_categorical(y_valid, num_classes=3)

In [7]:
X_train[0]

array([ 0.90714465, -1.55184099])

In [8]:
y_train

array([0, 2, 1, ..., 1, 2, 0], dtype=int64)

In [9]:
model = Sequential()

In [10]:
model.add(Dense(3, activation='relu', input_shape=(2,)))
model.add(Dense(2, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [11]:
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

In [12]:
print(X_train.shape, y_train.shape, X_valid.shape, y_valid.shape)

(1200, 2) (1200,) (300, 2) (300,)


In [16]:
model.fit(X_train, y_train_onehot, 
          batch_size=48, epochs=1000, verbose=1, 
          validation_data=(X_valid, y_valid_onehot))

Epoch 1/1000
25/25 [==============================] - 0s 4ms/step - loss: 0.3965 - accuracy: 0.8558 - val_loss: 0.3333 - val_accuracy: 0.8767
Epoch 2/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3962 - accuracy: 0.8567 - val_loss: 0.3329 - val_accuracy: 0.8800
Epoch 3/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3959 - accuracy: 0.8567 - val_loss: 0.3327 - val_accuracy: 0.8800
Epoch 4/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3952 - accuracy: 0.8558 - val_loss: 0.3322 - val_accuracy: 0.8767
Epoch 5/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3948 - accuracy: 0.8558 - val_loss: 0.3314 - val_accuracy: 0.8767
Epoch 6/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3946 - accuracy: 0.8558 - val_loss: 0.3308 - val_accuracy: 0.8767
Epoch 7/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3941 - accuracy: 0.8575 - val_loss: 0.3309 - val_accuracy: 0.8867
Epoch 

In [17]:
# Exporting the model
model.save('food.keras')

In [18]:
from keras.models import load_model
model = load_model('food.keras')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 9         
                                                                 
 dense_1 (Dense)             (None, 2)                 8         
                                                                 
 dense_2 (Dense)             (None, 3)                 9         
                                                                 
Total params: 26 (104.00 Byte)
Trainable params: 26 (104.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
