In [25]:
import keras
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD, Adam
from keras.utils import to_categorical

from sklearn.model_selection import train_test_split


In [26]:
data = np.load('food.npz')
x, y = data['x'], data['y']
x, y

(array([[-1.17273899, -1.74921225],
        [-1.32528414, -0.9805946 ],
        [ 0.84108223, -0.81966812],
        ...,
        [-0.22758009, -1.17369814],
        [-0.8487975 , -0.17594146],
        [ 1.09114043,  0.90788055]]),
 array([2, 2, 0, ..., 2, 2, 1], dtype=int64))

In [27]:
X_train, X_valid, y_train, y_valid = train_test_split(x, y, test_size=0.2)

In [28]:
y_train_onehot = to_categorical(y_train, num_classes=3)
y_valid_onehot = to_categorical(y_valid, num_classes=3)

In [29]:
X_train[0]

array([ 0.32504491, -1.59829442])

In [30]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
model = Sequential()

In [32]:
model.add(Dense(3, activation='relu', input_shape=(2,)))
model.add(Dense(2, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [33]:
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

In [34]:
print(X_train.shape, y_train.shape, X_valid.shape, y_valid.shape)

(1200, 2) (1200,) (300, 2) (300,)


In [35]:
model.fit(X_train, y_train_onehot, 
          batch_size=64, epochs=200, verbose=1, 
          validation_data=(X_valid, y_valid_onehot))

Epoch 1/200
19/19 [==============================] - 2s 52ms/step - loss: 1.0707 - accuracy: 0.5617 - val_loss: 1.0978 - val_accuracy: 0.5567
Epoch 2/200
19/19 [==============================] - 0s 13ms/step - loss: 1.0531 - accuracy: 0.5908 - val_loss: 1.0802 - val_accuracy: 0.5533
Epoch 3/200
19/19 [==============================] - 0s 14ms/step - loss: 1.0372 - accuracy: 0.5867 - val_loss: 1.0639 - val_accuracy: 0.5500
Epoch 4/200
19/19 [==============================] - 0s 15ms/step - loss: 1.0212 - accuracy: 0.5817 - val_loss: 1.0485 - val_accuracy: 0.5433
Epoch 5/200
19/19 [==============================] - 0s 14ms/step - loss: 1.0049 - accuracy: 0.5833 - val_loss: 1.0323 - val_accuracy: 0.5433
Epoch 6/200
19/19 [==============================] - 0s 14ms/step - loss: 0.9878 - accuracy: 0.5942 - val_loss: 1.0158 - val_accuracy: 0.5633
Epoch 7/200
19/19 [==============================] - 0s 9ms/step - loss: 0.9696 - accuracy: 0.6017 - val_loss: 0.9975 - val_accuracy: 0.5733
Epoch 8

In [ ]:
# Exporting the model
model.save('food.h5')