In [64]:
import keras
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD, Adam

from sklearn.model_selection import train_test_split


### A Hot Dog-Detecting Dense Network
Let’s further strengthen your comprehension of dense networks by returning to two old flames of ours from Chapter 6: a frivolous hot dog-detecting binary classifier and the mathematical notation we used to define artificial neurons. As shown in Figure 7.1, our hot dog classifier is no longer a single neuron; in this chapter, it is a dense network of artificial neurons. More specifically, with this network architecture, the following differences apply:

We have reduced the number of input neurons down to two for simplicity.

The first input neuron, x1, represents the volume of ketchup (in, say, milliliters, which abbreviates to mL) on the object being considered by the network. (We are no longer working with perceptrons, so we are no longer restricted to binary inputs only.)

The second input neuron, x2, represents milliliters of mustard.

We have two dense hidden layers.

The first hidden layer has three ReLU neurons.

The second hidden layer has two ReLU neurons.

The output neuron is denoted by y in the network. This is a binary classification problem, so—as outlined in the previous section—this neuron should be sigmoid. As in our perceptron examples in Chapter 6, y = 1 corresponds to the presence of a hot dog and y = 0 corresponds to the presence of some other object.



In [65]:
data = np.load('hotdog.npz')
x, y = data['x'], data['y']

In [66]:
x, y

(array([[ 0.44841152,  1.27441316],
        [ 1.23208152,  0.81482256],
        [-1.1495249 ,  1.21871837],
        ...,
        [ 0.36841718, -0.37785125],
        [ 1.1413017 ,  1.06117385],
        [ 1.50360507,  0.89986583]]),
 array([1, 1, 0, ..., 0, 1, 1], dtype=int64))

In [67]:
# Split data into training and testing
X_train, X_valid, y_train, y_valid = train_test_split(x, y, test_size=0.2)

In [68]:
X_train[0]

array([-1.30567006, -0.43935684])

In [69]:
y_test

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0], d

In [70]:
model = Sequential()

In [71]:
model.add(Dense(3, input_shape=(2,), activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [72]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [73]:
model.fit(X_train, y_train,
          batch_size=256, epochs=200,
          verbose=1,
          validation_data=(X_valid, y_valid))

Epoch 1/200
5/5 [==============================] - 3s 111ms/step - loss: 0.6392 - accuracy: 0.4842 - val_loss: 0.6286 - val_accuracy: 0.6667
Epoch 2/200
5/5 [==============================] - 0s 39ms/step - loss: 0.6362 - accuracy: 0.6458 - val_loss: 0.6255 - val_accuracy: 0.7500
Epoch 3/200
5/5 [==============================] - 0s 37ms/step - loss: 0.6333 - accuracy: 0.6833 - val_loss: 0.6225 - val_accuracy: 0.7667
Epoch 4/200
5/5 [==============================] - 0s 38ms/step - loss: 0.6303 - accuracy: 0.6967 - val_loss: 0.6193 - val_accuracy: 0.7833
Epoch 5/200
5/5 [==============================] - 0s 37ms/step - loss: 0.6274 - accuracy: 0.7142 - val_loss: 0.6162 - val_accuracy: 0.8000
Epoch 6/200
5/5 [==============================] - 0s 38ms/step - loss: 0.6245 - accuracy: 0.7275 - val_loss: 0.6131 - val_accuracy: 0.8267
Epoch 7/200
5/5 [==============================] - 0s 36ms/step - loss: 0.6216 - accuracy: 0.7483 - val_loss: 0.6100 - val_accuracy: 0.8367
Epoch 8/200
5/5 [==

In [74]:
loss, accuracy = model.evaluate(x, y)
print(f"Loss: {loss}, Accuracy: {accuracy}")

47/47 [==============================] - 0s 4ms/step - loss: 0.2118 - accuracy: 0.9280
Loss: 0.21183136105537415, Accuracy: 0.9279999732971191


In [ ]:
# Exporting model
movel.save('hotdog.h5')