In [24]:
import keras
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD, Adam

from sklearn.model_selection import train_test_split


### A Hot Dog-Detecting Dense Network
Let’s further strengthen your comprehension of dense networks by returning to two old flames of ours from Chapter 6: a frivolous hot dog-detecting binary classifier and the mathematical notation we used to define artificial neurons. As shown in Figure 7.1, our hot dog classifier is no longer a single neuron; in this chapter, it is a dense network of artificial neurons. More specifically, with this network architecture, the following differences apply:

We have reduced the number of input neurons down to two for simplicity.

The first input neuron, x1, represents the volume of ketchup (in, say, milliliters, which abbreviates to mL) on the object being considered by the network. (We are no longer working with perceptrons, so we are no longer restricted to binary inputs only.)

The second input neuron, x2, represents milliliters of mustard.

We have two dense hidden layers.

The first hidden layer has three ReLU neurons.

The second hidden layer has two ReLU neurons.

The output neuron is denoted by y in the network. This is a binary classification problem, so—as outlined in the previous section—this neuron should be sigmoid. As in our perceptron examples in Chapter 6, y = 1 corresponds to the presence of a hot dog and y = 0 corresponds to the presence of some other object.



In [25]:
data = np.load('hotdog.npz')
x, y = data['x'], data['y']

In [26]:
x, y

(array([[ 0.44841152,  1.27441316],
        [ 1.23208152,  0.81482256],
        [-1.1495249 ,  1.21871837],
        ...,
        [ 0.36841718, -0.37785125],
        [ 1.1413017 ,  1.06117385],
        [ 1.50360507,  0.89986583]]),
 array([1, 1, 0, ..., 0, 1, 1], dtype=int64))

In [27]:
# Split data into training and testing
X_train, X_valid, y_train, y_valid = train_test_split(x, y, test_size=0.2)

In [28]:
X_train[0]

array([0.48492337, 1.31197638])

In [29]:
y_valid

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], d

In [30]:
model = Sequential()

In [31]:
model.add(Dense(3, input_shape=(2,), activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [32]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [33]:
y_train.shape

(1200,)

In [34]:
y_valid.shape

(300,)

In [36]:
model.fit(X_train, y_train,
          batch_size=48, epochs=1000,
          verbose=1,
          validation_data=(X_valid, y_valid))

Epoch 1/1000
25/25 [==============================] - 0s 4ms/step - loss: 0.3532 - accuracy: 0.9183 - val_loss: 0.3644 - val_accuracy: 0.8867
Epoch 2/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3491 - accuracy: 0.9175 - val_loss: 0.3608 - val_accuracy: 0.8867
Epoch 3/1000
25/25 [==============================] - 0s 4ms/step - loss: 0.3451 - accuracy: 0.9192 - val_loss: 0.3579 - val_accuracy: 0.8867
Epoch 4/1000
25/25 [==============================] - 0s 4ms/step - loss: 0.3413 - accuracy: 0.9192 - val_loss: 0.3546 - val_accuracy: 0.8900
Epoch 5/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3380 - accuracy: 0.9183 - val_loss: 0.3507 - val_accuracy: 0.8967
Epoch 6/1000
25/25 [==============================] - 0s 3ms/step - loss: 0.3345 - accuracy: 0.9183 - val_loss: 0.3487 - val_accuracy: 0.8933
Epoch 7/1000
25/25 [==============================] - 0s 4ms/step - loss: 0.3311 - accuracy: 0.9175 - val_loss: 0.3459 - val_accuracy: 0.8967
Epoch 

In [37]:
loss, accuracy = model.evaluate(x, y)
print(f"Loss: {loss}, Accuracy: {accuracy}")

47/47 [==============================] - 0s 1ms/step - loss: 0.1281 - accuracy: 0.9620
Loss: 0.12810572981834412, Accuracy: 0.9620000123977661


In [39]:
# Exporting model
model.save('hotdog.keras')

In [42]:
from keras.models import load_model
model = load_model('food.keras')

In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 9         
                                                                 
 dense_1 (Dense)             (None, 2)                 8         
                                                                 
 dense_2 (Dense)             (None, 3)                 9         
                                                                 
Total params: 26 (104.00 Byte)
Trainable params: 26 (104.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
